### ISSUE TITLE
Allow hostnames in addition to IP addresses for connecting to WLED devices

### ISSUE THREAD

**Issue by lhmiller** [timstoddard/WLED-web-client-angular#81]
Currently only IP addresses are allowed, but it would be nice to be able to use hostnames as well. Also, if/when WLED supports secure connections, the URL will need to match the SAN on the certificate to avoid certificate errors.

**Comment by timstoddard** [comment]
resolved by https://github.com/timstoddard/WLED-web-client-angular/commit/660107eddb82b5ecc7d978857d0bc74af2b8e0db
